services:
  apc_service:
    build: .
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    environment:
      - GST_DEBUG=webrtc*:6
    ports:
      - 3478:3478/udp 
      - 19302:19302/udp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge